[package]
name = "network_simulator"
version = "0.1.0"
authors = ["shayan <shafaghi1378@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
